# Generated by Django 4.1.1 on 2022-09-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accholder',
            name='acc_type',
            field=models.CharField(choices=[('S', 'Savings'), ('C', 'Current')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=954871810, unique=True),
        ),
    ]
