# Generated by Django 4.1.1 on 2022-09-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_accholder_acc_type_alter_accholder_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accholder',
            name='aadhaar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accholder',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accholder',
            name='pan',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=948060208, unique=True),
        ),
    ]
