# Generated by Django 4.1.1 on 2022-09-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_accholder_aadhaar_accholder_balance_accholder_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=89848588, unique=True),
        ),
    ]
