# Generated by Django 4.1.1 on 2022-09-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_accholder_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=832422904, unique=True),
        ),
        migrations.AlterField(
            model_name='accholder',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
