# Generated by Django 4.1.1 on 2022-09-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_alter_accholder_account_number_alter_accholder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accholder',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accholder',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=784657616, unique=True),
        ),
    ]
