# Generated by Django 4.1.1 on 2022-09-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0018_alter_accholder_account_number_alter_accholder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=972642274, unique=True),
        ),
    ]
