# Generated by Django 4.1.1 on 2022-09-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0020_alter_accholder_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='t_type',
            field=models.CharField(choices=[('Deposited', 'Deposit'), ('Withdrawn', 'Withdraw')], default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=931866446, unique=True),
        ),
    ]
