# Generated by Django 4.1.1 on 2022-09-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0021_transactions_t_type_alter_accholder_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=523235640, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='reciver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='banking.accholder'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='t_type',
            field=models.CharField(choices=[('Deposited', 'Deposit'), ('Withdrawn', 'Withdraw')], max_length=9, null=True),
        ),
    ]
