# Generated by Django 4.1.1 on 2022-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0022_alter_accholder_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=497870826, unique=True),
        ),
    ]
