# Generated by Django 4.1.1 on 2022-09-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0023_alter_accholder_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='reciver',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='transfer_date',
        ),
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=359614973, unique=True),
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transfer_date', models.DateTimeField(auto_now=True)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='banking.accholder')),
            ],
        ),
    ]
