# Generated by Django 4.1.1 on 2022-09-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0024_remove_transactions_reciver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=720403367, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='t_type',
            field=models.CharField(choices=[('Deposited', 'Deposit'), ('Withdrawn', 'Withdraw')], default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.accholder'),
        ),
    ]
