# Generated by Django 4.1.1 on 2022-09-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0025_alter_accholder_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='banking.accholder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accholder',
            name='account_number',
            field=models.IntegerField(default=267602995, unique=True),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='banking.accholder'),
        ),
    ]
